#!/usr/bin/env bash

cat << "EOF"
░░░░▄▄▄▄▄▓▓▓▄▄▄░░░░░
░░░░▄▄▓▀▀▀▀▀▀▓▓▓▓▓▓▄░░░
░░▄▄▓▀▀░░░░░░░░░░░░▀▓▄░
░▐▓▓▌░░░░░░▄▄▄▄▄░░░░░▓▌
░▐▓▒░░░░░░█░▒◐▒░█░░░░░▓
░▓▓▌░░░░░░░▀▀▀▀▀░░░░░▒▓
░▐▓░░░░░░░░░░░░░░░░▒▒▒▓
█░▀▄░█▄█▀▄▄░▀░▀▄▄▀░░█░█
░█░░░▀▄█▄█░█▀▄▄▄▄▄▀██░█
░░█░░░░█░███▄█▄█▄███░░█
░░░█░░░▀▀█░█▀█▀█▀███░█
░░░░▀▄░░░░▀▀▄█▄█▄█▄▀░█
░░░░░░▀▄▄░▒▒▒░░░░░░░░░█
░░░░░░░░░▀▀▄▄▄▄▄▄▄▄▄▄▀
EOF

##############################################
# Appearence
##############################################
RED=$(tput setaf 1)
YELLOW=$(tput setaf 3)
RESET=$(tput sgr0)
MESSAGES=("${RED}[1] ${YELLOW}Setting up environment."
          "${RED}[2] ${YELLOW}Copying files."
          "${RED}[3] ${YELLOW}Compressing files."
          "${RED}[4] ${YELLOW}Finalizing.")

##############################################
# Environment Setup
##############################################

echo -e "\n${MESSAGES[0]}"

LOG="/tmp/backup/$(date +"%y-%m-%d").log"
DESTINATION="/tmp/backup/$(date +"%y-%m-%d")"
mkdir -p /tmp/backup/$dest 
cd $_ 
chmod 700 /tmp/backup
sleep 1

##############################################
# Copy and Arciving of Files
##############################################

full_backup() {
cat << "EOF" > $LOG
*--------------------------------------------*
* Full Backup Started at $(date +"%H:%M:%S")
*
* Source:      $(SOURCE_FOLDER)
* Destination: $DESTINATION
*
* -------------------------------------------*
EOF 

rsync -aAXvz --log-file=$LOG $SOURCE_FOLDER \
--exclude="/home/*"  \
--exclude="/dev/*"  \
--exclude="/proc/*" \
--exclude=".Trash*/*" \
--exclude="/sys/*" \
--exclude="/tmp/*" \
--exclude="/run/*" \
--exclude="/mnt/*" \
--exclude="/usr/*" \
--exclude="/media/*" \
--exclude="/lost+found/*" . | \
       tqdm --total $(find . -type f | wc -l) --unit files

if [[ $? -eq 0 ]]; then
  echo "@ Error copying, please see $LOG for more details." ; \
  exit 1
fi
}

specific_backup() {
cat << "EOF" > $LOG
*--------------------------------------------*
* Specific Backup Started at $(date +"%H:%M:%S")
*
* Source:      $(SOURCE_FOLDER)
* Destination: $DESTINATION
*
* -------------------------------------------*
EOF 

rsync -aAXvz  --log-file=$LOG $SOURCE_FOLDER $DESTINATION | \
  tqdm --total $(find . -type f | wc -l) --unit files

if [[ $? -eq 0 ]]; then
    echo "@ Error copying, please see $LOG for more details." ; \
    exit 1
fi
}





echo -e "${MESSAGES[1]}\n" 

echo -e "Rsync Copy Results\n" > /tmp/backup/$log 



sleep 1

echo -e "\n${MESSAGES[2]}\n"
cd .. 
echo -e "\nTaring Directory\n" >> $log
tar -cvzf "${dest}.tar.gz" "$dest" | \
    tqdm --unit_scale | wc -l >> "$log" || \
    echo "@ Error compressing. Please see $log for more details." ; \
    exit 1

sleep 1

echo -e "\n${MESSAGES[3]}"


